parameters:
- name: environment
  default: 'dev'

stages:
- stage: ${{ parameters.environment }}_deploy

  variables:
  - group: 'xi-portal-${{ parameters.environment }}'
  - name: 'environment'
    value: ${{ parameters.environment }}

  jobs:
  - deployment: A
    pool:
      vmImage: 'ubuntu-latest'
    environment: staging
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]this is the deployment variable value"
            name: setvarStep
          - script: echo $(setvarStep.myOutputVar)
            name: echovar

  # Map the variable from the job for the first slice
  - job: B
    dependsOn: A
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      myVarFromDeploymentJob: $[ dependencies.A.outputs['A.setvarStep.myOutputVar'] ]
    steps:
    - script: "echo $(myVarFromDeploymentJob)"
      name: echovar

  - deployment: terraform_deploy

    pool:
      vmImage: 'ubuntu-latest'

    environment: 'xi-portal-${{ parameters.environment }}'

    strategy:
     runOnce:
       deploy:
        steps:
          - download: current
            displayName: 'Download terraform source artifact'
            artifact: terraform

          - task: TerraformInstaller@0
            displayName: 'Install terraform'
            inputs:
              terraformVersion: '0.12.24'

          - task: TerraformTaskV1@0
            displayName: 'Terraform: azurerm init'
            inputs:
              workingDirectory: '$(Pipeline.Workspace)/terraform'
              backendServiceArm: 'XI-Pay-As-You-Go'
              backendAzureRmResourceGroupName: '$(AzTerraformResourceGroup)'
              backendAzureRmStorageAccountName: '$(AzTerraformStorageAccount)'
              backendAzureRmContainerName: terraform
              backendAzureRmKey: '${{ parameters.environment }}-terraform.tfstate'

          - task: TerraformTaskV1@0
            displayName: 'Terraform : azurerm plan'
            inputs:
              command: plan
              workingDirectory: '$(Pipeline.Workspace)/terraform'
              commandOptions: '-var="environment=$(environment)"'
              environmentServiceNameAzureRM: 'XI-Pay-As-You-Go'

          - task: TerraformTaskV1@0
            name: terraform_validate_and_apply
            displayName: 'Terraform : azurerm validate and apply'
            inputs:
              command: apply
              workingDirectory: '$(Pipeline.Workspace)/terraform'
              commandOptions: '-var="environment=$(environment)"'
              environmentServiceNameAzureRM: 'XI-Pay-As-You-Go'

          - script: "echo $(identity_storage_connection)"
            name: echovar1

          - script: "echo $(terraform_validate_and_apply.identity_storage_connection)"
            name: echovar2

          - script: "echo $('terraform_validate_and_apply.identity_storage_connection')"
            name: echovar3

  - deployment: 'webapp_deploy'
    dependsOn: 'terraform_deploy'
    pool: 
      vmImage: 'windows-latest'

    environment: 'xi-portal-${{ parameters.environment }}'

    variables:
    - name: identity_storage_connection
      value: $[ dependencies.terraform_deploy.outputs['terraform_deploy.terraform_validate_and_apply.identity_storage_connection'] ]

    strategy:
     runOnce:
       deploy:
         steps:
          - download: current
            displayName: 'Download webapp artifact'
            artifact: webapp

          - task: AzureRmWebAppDeployment@4
            displayName: 'Azure App Service Deploy: XI-Portal-WebApp-$(environment)'
            inputs:
              azureSubscription: 'XI-Pay-As-You-Go'
              WebAppName: 'XI-Portal-WebApp-$(environment)'
              deployToSlotOrASE: true
              ResourceGroupName: 'XI-Portal-Web-$(environment)'
              packageForLinux: '$(Pipeline.Workspace)/webapp/XI.Portal.Web.zip'
              AppSettings: '-ApplicationAuthDbContext:StorageConnectionString "$(identity_storage_connection)"'
