parameters:
- name: environment
  default: 'dev'

stages:
- stage: ${{ parameters.environment }}_deploy

  variables:
  - group: 'xi-portal-${{ parameters.environment }}'
  - name: 'environment'
    value: ${{ parameters.environment }}

  jobs:
  - deployment: terraform_deploy

    pool:
      vmImage: 'ubuntu-latest'

    environment: 'xi-portal-${{ parameters.environment }}'

    strategy:
     runOnce:
       deploy:
        steps:
          - download: current
            displayName: 'Download terraform source artifact'
            artifact: terraform

          - task: TerraformInstaller@0
            displayName: 'Install terraform'
            inputs:
              terraformVersion: '0.12.24'

          - task: TerraformTaskV1@0
            displayName: 'Terraform: azurerm init'
            inputs:
              workingDirectory: '$(Pipeline.Workspace)/terraform'
              backendServiceArm: 'XI-Pay-As-You-Go'
              backendAzureRmResourceGroupName: '$(AzTerraformResourceGroup)'
              backendAzureRmStorageAccountName: '$(AzTerraformStorageAccount)'
              backendAzureRmContainerName: terraform
              backendAzureRmKey: '${{ parameters.environment }}-terraform.tfstate'

          - task: TerraformTaskV1@0
            displayName: 'Terraform : azurerm plan'
            inputs:
              command: plan
              workingDirectory: '$(Pipeline.Workspace)/terraform'
              commandOptions: '-var="environment=$(environment)"'
              environmentServiceNameAzureRM: 'XI-Pay-As-You-Go'

          - task: TerraformTaskV1@0
            name: terraform_validate_and_apply
            displayName: 'Terraform : azurerm validate and apply'
            inputs:
              command: apply
              workingDirectory: '$(Pipeline.Workspace)/terraform'
              commandOptions: '-var="environment=$(environment)"'
              environmentServiceNameAzureRM: 'XI-Pay-As-You-Go'

          - powershell: |
              $terraformOutput = Get-Content "$(terraform_validate_and_apply.jsonOutputVariablesPath)" | ConvertFrom-Json
              $terraformOutput | Get-Member -MemberType NoteProperty | % { $o = $terraformOutput.($_.Name); Write-Host "##vso[task.setvariable variable=$($_.Name);isoutput=true;issecret=$($o.sensitive)]$($o.value)" }
            name: terraform_output
            displayName: 'Read terraform output vars'

  - deployment: 'webapp_deploy'
    dependsOn: 'terraform_deploy'
    pool: 
      vmImage: 'windows-latest'

    environment: 'xi-portal-${{ parameters.environment }}'

    variables:
    - name: identity_storage_connection
      value: $[ dependencies.terraform_deploy.outputs['terraform_deploy.terraform_output.identity_storage_connection'] ]
    - name: appdata_storage_connection
      value: $[ dependencies.terraform_deploy.outputs['terraform_deploy.terraform_output.appdata_storage_connection'] ]

    strategy:
     runOnce:
       deploy:
         steps:
          - download: current
            displayName: 'Download webapp artifact'
            artifact: webapp

          - task: AzureRmWebAppDeployment@4
            displayName: 'Azure App Service Deploy: XI-Portal-WebApp-$(environment)'
            inputs:
              azureSubscription: 'XI-Pay-As-You-Go'
              WebAppName: 'XI-Portal-WebApp-$(environment)'
              deployToSlotOrASE: true
              ResourceGroupName: 'XI-Portal-Web-$(environment)'
              packageForLinux: '$(Pipeline.Workspace)/webapp/XI.Portal.Web.zip'
              AppSettings: '-ApplicationAuthDbContext:StorageConnectionString "$(identity_storage_connection)" -XtremeIdiotsAuth:ClientId "$(XtremeIdiotsAuth:ClientId)" -XtremeIdiotsAuth:ClientSecret "$(XtremeIdiotsAuth:ClientSecret)" -AppDataContainer:StorageConnectionString "$(appdata_storage_connection)" -XtremeIdiotsForums:ApiKey "$(XtremeIdiotsForums:ApiKey)" -LegacyPortalContext:ConnectionString "$(LegacyPortalContext:ConnectionString)"  -GeoLocation:BaseUrl "$(GeoLocation:BaseUrl)" -GeoLocation:ApiKey "$(GeoLocation:ApiKey)"'

  - deployment: 'funcapp_deploy'
    dependsOn: 'terraform_deploy'
    pool: 
      vmImage: 'windows-latest'

    environment: 'xi-portal-${{ parameters.environment }}'

    variables:
    - name: appdata_storage_connection
      value: $[ dependencies.terraform_deploy.outputs['terraform_deploy.terraform_output.appdata_storage_connection'] ]

    strategy:
     runOnce:
       deploy:
         steps:
          - download: current
            displayName: 'Download funcapp artifact'
            artifact: funcapp

          - task: AzureFunctionApp@1
            displayName: 'Azure Function App Deploy: XI-Portal-FuncApp-$(Environment)'
            inputs:
              azureSubscription: 'XI-Pay-As-You-Go'
              appType: functionAppLinux
              appName: 'XI-Portal-FuncApp-$(environment)'
              deployToSlotOrASE: true
              resourceGroupName: 'XI-Portal-Web-$(environment)'
              package: '$(Pipeline.Workspace)/funcapp/XI.Portal.FuncApp.zip'
              runtimeStack: 'DOCKER|microsoft/azure-functions-dotnet-core2.0:2.0'
              AppSettings: '-AppDataContainer:StorageConnectionString "$(appdata_storage_connection)" -LegacyPortalContext:ConnectionString "$(LegacyPortalContext:ConnectionString)" -GeoLocation:BaseUrl "$(GeoLocation:BaseUrl)" -GeoLocation:ApiKey "$(GeoLocation:ApiKey)" -MapsRedirect:ApiKey "$(MapsRedirect:ApiKey)"'