parameters:
- name: jobName
  type: string
  default: BuildWebApp
- name: dependsOn
  type: object
  default: []
- name: publishArtifact
  type: boolean
  default: false
- name: projectName
  type: string
  default: 'web-app'
- name: nugetConfigPath
  type: string
  default: ''


jobs:
- job: ${{ parameters.jobName }}
  dependsOn: ${{ parameters.dependsOn }}

  variables:
    buildConfiguration: 'Release'

  steps:
  - task: UseDotNet@2
    inputs:
      version: 6.0.x
      performMultiLevelLookup: true
      includePreviewVersions: true
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/${{ parameters.projectName }}.csproj'
      ${{ if ne(parameters.nugetConfigPath, '') }}:
        feedsToUse: 'config'
        nugetConfigPath: ${{ parameters.nugetConfigPath }}

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/${{ parameters.projectName }}.csproj'
      arguments: '--configuration $(buildConfiguration)'
    displayName: 'dotnet build $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    condition: and(succeeded(), eq('${{ parameters.publishArtifact }}', 'true'))
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/${{ parameters.projectName }}.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/${{ parameters.projectName }}.zip'
    displayName: 'dotnet publish $(buildConfiguration)'

  - publish: '$(Build.artifactStagingDirectory)/${{ parameters.projectName }}.zip'
    condition: and(succeeded(), eq('${{ parameters.publishArtifact }}', 'true'))
    displayName: Publish ${{ parameters.projectName }} artifact
    artifact: ${{ parameters.projectName }}